import type { Metadata } from "next";
import "./globals.css";
import { Outfit, Inter, Space_Grotesk } from "next/font/google";
import { MapProvider } from "@/components/context/MapContext";
import { AuthProvider } from "@/components/context/AuthProvider";
import ConsoleLoggerSilencer from "@/components/context/ConsoleLoggerSilencer";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-outfit",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-inter",
});

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
  variable: "--font-space",
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Squamish Real Estate",
  description: "Generated by create next app",
  icons: {
    icon: "/images/icon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} ${inter.variable} ${spaceGrotesk.variable}`}
      >
        <AuthProvider>
          <MapProvider>
            <ConsoleLoggerSilencer />
            {children}
          </MapProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
